### ISSUE TITLE
Function transfer should revert in case of insufficient balance 

### ISSUE THREAD

**Issue by yuriy77k** [Dexaran/CallistoDAO#1]
Since most contracts don't check the return value of the transfer() function, better to revert transaction in case of error.

https://github.com/Dexaran/CallistoDAO/blob/c3e4a2751c6addd59d7e6dc725773c55c3072acf/CallistoDAOv1.sol#L67

replace with:
```Solidity
revert("insufficient balance");
```

**Comment by Dexaran** [comment]
Yes, you are right

I will revisit the token logic (and support ERC223 transferring mechanics) in the next update

Right now it's just "interface" (to check if removing approvals caused some problems on internal logic of the DAO contract)

**Comment by Dexaran** [comment]
Also I don't think it was a good idea to merge Token and DAO logic in one contract.
I would extract token to separate contract but it will result in the necessity of cross-contract calls (to update already-paid share of DAO dividents)

So it's still an idea

**Comment by yuriy77k** [comment]
I don't see any issues to have Token and DAO logic in the same contract. Many DeFi do like that (for example, liquidity pool has  LP token in the same contract)

**Comment by Dexaran** [comment]
I still don't think it is a good idea to mix two different parts of logic in one contract.

But now it would require to rewrite a significant part of code to separate them and it is not really that important
